@extends('admin.layouts.app')
@section('content')
    <div class="page-content">
        <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
            <div>
                <h4 class=" mb-md-0">DYNAMIC EMPIRE - <span class="text-primary">ALL CALL REQUESTS</span></h4>
            </div>
            <div class="d-flex align-items-center flex-wrap text-nowrap">
                @if($Role == 1)
                    <button type="button" class="btn btn-primary btn-icon-text mb-md-0"
                            onclick="window.location.href='{{url('admin/call-request/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        New Call Request
                    </button>
                @elseif($Role == 2)
                    <button type="button" class="btn btn-primary btn-icon-text mb-md-0"
                            onclick="window.location.href='{{url('general_manager/call-request/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        New Call Request
                    </button>
                @elseif($Role == 3)
                    <button type="button" class="btn btn-primary btn-icon-text mb-md-0"
                            onclick="window.location.href='{{url('confirmationAgent/call-request/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        New Call Request
                    </button>
                @elseif($Role == 4)
                    <button type="button" class="btn btn-primary btn-icon-text mb-md-0"
                            onclick="window.location.href='{{url('supervisor/call-request/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        New Call Request
                    </button>
                @elseif($Role == 5)
                    <button type="button" class="btn btn-primary btn-icon-text mb-md-0"
                            onclick="window.location.href='{{url('representative/call-request/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        New Call Request
                    </button>
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-12 mb-3">
                @if(session()->has('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @elseif(session()->has('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
            </div>

            @if($Role == 1 || $Role == 2 || $Role == 3)
                <div class="col-md-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">
                                Leads
                            </h6>
                            <div class="row mt-3 mb-4">
                              <div class="col-md-3">
                                <div class="">
                                  <select class="form-control" name="filter_lead_type" id="filter_lead_type" onchange="MakeAdminCallRequestsTable();">
                                    <option value="" selected>All</option>
                                    <option value="2">Call Request</option>
                                    <option value="3">Dispo Lead</option>
                                  </select>
                                </div>
                              </div>
                            </div>
                            <div class="table-responsive">
                                <table id="admin_callrequests_table" class="table w-100">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Generated By</th>
                                        <th>Lead Number</th>
                                        <th>Name</th>
                                        <th>Phone 1</th>
                                        <th>Appointment time</th>
                                        <th>Duplicated</th>
                                        <th>Type</th>
                                        <th>Action</th>
                                        <th>Convert to Lead</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            @elseif($Role == 4 || $Role == 5)
                <div class="col-md-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">
                                Leads
                            </h6>
                            <div class="table-responsive">
                                <table id="representative_callrequests_table" class="table w-100">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Generated By</th>
                                        <th>Lead Number</th>
                                        <th>Name</th>
                                        <th>Phone 1</th>
                                        <th>Appointment Time</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
    @include('admin.includes.convertToLeadModal')
    @include('admin.includes.convertDispoLeadToLead')
@endsection
