@extends('admin.layouts.app')
@section('content')
<div class="page-content">
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class=" mb-md-0">DYNAMIC EMPIRE - <span class="text-primary">ALL DISPO LEADS</span></h4>
        </div>
        <!-- <div class="d-flex align-items-center flex-wrap text-nowrap">
        </div> -->
    </div>

    <div class="row">
        <div class="col-12 mb-3">
            @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
            @elseif(session()->has('error'))
            <div class="alert alert-danger">
                {{ session('error') }}
            </div>
            @endif
        </div>

        @if($Role == 1 || $Role == 2 || $Role == 3)
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">
                        Dispo Leads
                    </h6>
                    <div class="table-responsive">
                        <table id="admin_dispoleads_table" class="table w-100">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Generated By</th>
                                    <th>Lead Number</th>
                                    <th>Name</th>
                                    <th>Phone 1</th>
                                    <th>Appointment time</th>
                                    <th>Duplicated</th>
                                    <th>Action</th>
                                    <th>Convert to Lead</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @elseif($Role == 4 || $Role == 5)
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">
                        Leads
                    </h6>
                    <div class="table-responsive">
                        <table id="representative_dispoleads_table" class="table w-100">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Generated By</th>
                                    <th>Lead Number</th>
                                    <th>Name</th>
                                    <th>Phone 1</th>
                                    <th>Appointment Time</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
</div>
@include('admin.includes.convertDispoLeadToLead')
@endsection
