@extends('admin.layouts.app')
@section('content')
    <div class="page-content" id="SalesPage">
        <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
            <div>
                <h4 class="mb-3 mb-md-0">Elite Empire - <span class="text-primary">Sales</span></h4>
            </div>
            {{--<div class="d-flex align-items-center flex-wrap text-nowrap">
                @if($Role == 1)
                    <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0"
                            onclick="window.location.href='{{url('admin/sale/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        Add New Sale
                    </button>
                @elseif($Role == 2)
                    <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0"
                            onclick="window.location.href='{{url('global_manager/sale/add')}}';">
                        <i class="fas fa-plus-square mr-1"></i>
                        Add New Sale
                    </button>
                @endif
            </div>--}}
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                @if(session()->has('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @elseif(session()->has('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
            </div>

            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title">
                            Details
                        </h6>
                        <div class="table-responsive">
                            <table id="lead_sales_table" class="table w-100">
                                <thead>
                                <tr>
                                    <th>Sr. No.</th>
                                    <th>Generated By</th>
                                    <th>Lead Number</th>
                                    <th>Sale Type</th>
                                    <th>Contract Amount</th>
                                    <th>Contract Date</th>
                                    <th>Net Profit (%)</th>
                                    <th>Net Profit Amount</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('admin.includes.viewSaleModal')
    @include('admin.includes.addSaleModal')
    @include('admin.includes.approvePayrollModal')
    @include('admin.includes.rollbackPayrollModal')
@endsection